apiVersion: apps/v1
kind: Deployment
metadata:
  name: mssql-leader
  labels:
    app: mssql
    role: leader
    tier: backend
spec:
  replicas: 1
  selector:
    matchLabels:
      app: mssql
  template:
    metadata:
      labels:
        app: mssql
        role: leader
        tier: backend
    spec:
      hostname: mssqlinst
      securityContext:
        fsGroup: 10001
      containers:
        - name: sql1
          image: "mcr.microsoft.com/mssql/server:2019-latest"
          env:
          - name: MSSQL_PID
            value: "Developer"
          - name: ACCEPT_EULA
            value: "Y"
          - name: SA_PASSWORD
            value: "Passssss12@@"
          ports:
          - containerPort: 1433
          volumeMounts:
          - name: mssql-storage
            mountPath: /var/opt/mssql
      volumes:
        - name: mssql-storage
          persistentVolumeClaim:
            claimName: mssql-volume-claim