apiVersion: v1
kind: Service
metadata:
  name: mssql-service
  labels:
    app: mssql
    tier: backend
spec:
  type: LoadBalancer
  ports:
    - protocol: TCP
      port: 1433
      targetPort: 1433
  selector:
    app: mssql
    tier: backend